blueprint:
  name: "🚪 Master Door Monitor (Areas, Floors, & Labels)"
  author: "3lB4rto"
  description: "Select any combination of doors, areas, floors, or labels. Notifies which are open and repeats every 3 minutes."
  domain: automation
  input:
    monitoring_targets:
      name: 🏠 Targets to Monitor
      selector:
        target:
          entity:
            domain: binary_sensor
            device_class: 
              - door
              - window
              - opening
    notify_devices:
      name: 📲 Notification Devices
      selector:
        device:
          filter:
            integration: mobile_app
          multiple: true
    reminder_interval:
      name: ⏳ Reminder Interval
      default: 3
      selector:
        number:
          min: 1
          max: 60
          unit_of_measurement: minutes
    initial_delay:
      name: ⏰ Time before first alert
      default: 0
      selector:
        duration:

mode: restart

trigger:
  # Using a template trigger to monitor any binary_sensor turning on
  - platform: template
    value_template: >
      {{ states.binary_sensor 
         | selectattr('state', 'eq', 'on') 
         | list | count > 0 }}

variables:
  targets: !input monitoring_targets
  notify_devices: !input notify_devices

action:
  - variables:
      # Expand targets into a list of entity IDs
      monitored_entities: >
        {% set ns = namespace(entities=[]) %}
        {% set t = targets %}
        {% if t.entity_id is defined %}
          {% set ids = [t.entity_id] if t.entity_id is string else t.entity_id %}
          {% set ns.entities = ns.entities + ids %}
        {% endif %}
        {% if t.area_id is defined %} 
          {% set areas = [t.area_id] if t.area_id is string else t.area_id %}
          {% for a in areas %}
            {% set ns.entities = ns.entities + area_entities(a) %}
          {% endfor %}
        {% endif %}
        {% if t.floor_id is defined %}
          {% set floors = [t.floor_id] if t.floor_id is string else t.floor_id %}
          {% for f in floors %}
            {% set ns.entities = ns.entities + floor_entities(f) %}
          {% endfor %}
        {% endif %}
        {% if t.label_id is defined %}
          {% set labels = [t.label_id] if t.label_id is string else t.label_id %}
          {% for l in labels %}
            {% set ns.entities = ns.entities + label_entities(l) %}
          {% endfor %}
        {% endif %}
        {{ ns.entities | unique | select('search', 'binary_sensor') | list }}

  # Check if at least one of OUR monitored entities is actually 'on'
  - condition: template
    value_template: >
      {{ expand(monitored_entities) | selectattr('state', 'eq', 'on') | list | count > 0 }}

  - delay: !input initial_delay

  # The main reminder loop
  - repeat:
      while:
        - condition: template
          value_template: "{{ expand(monitored_entities) | selectattr('state', 'eq', 'on') | list | count > 0 }}"
      sequence:
        - variables:
            open_names: "{{ expand(monitored_entities) | selectattr('state', 'eq', 'on') | map(attribute='name') | join(', ') }}"

        - repeat:
            for_each: "{{ notify_devices }}"
            sequence:
              - service: "notify.mobile_app_{{ device_attr(repeat.item, 'name') | slugify }}"
                data:
                  title: "⚠️ Security Alert"
                  message: "The following are still open: {{ open_names }}"
                  data:
                    tag: "multi_door_monitor"
                    group: "security-reminders"

        - delay:
            minutes: !input reminder_interval

  # Clear notifications when all sensors are back to 'off'
  - repeat:
      for_each: "{{ notify_devices }}"
      sequence:
        - service: "notify.mobile_app_{{ device_attr(repeat.item, 'name') | slugify }}"
          data:
            message: "clear_notification"
            data:
              tag: "multi_door_monitor"
