blueprint:
  name: "Daily Battery Health Monitor"
  description: >
    Checks all devices using the Battery Notes integration twice a day.
    
    If a device is low or stops reporting, it triggers the notification action you define.
  domain: automation
  author: 3lB4rto
  homeassistant:
    min_version: 2024.1.0
  input:
    time_check_1:
      name: First Check Time
      description: Time to run the first daily scan.
      default: "10:00:00"
      selector:
        time: {}
    time_check_2:
      name: Second Check Time
      description: Time to run the second daily scan.
      default: "17:00:00"
      selector:
        time: {}
    offline_days:
      name: Offline Threshold
      description: >
        Set to 1 to alert if a device hasn't reported in over 24 hours.
      default: 1
      selector:
        number:
          min: 1
          max: 30
          unit_of_measurement: days
          mode: slider
    notification_action:
      name: Notification Action
      description: >
        Choose your device/phone here. 
        IMPORTANT: In the Message field, type `{{ message }}` and in the Title field type `{{ title }}`.
      selector:
        action: {}

mode: queued
max: 10

trigger:
  - trigger: time
    at: !input time_check_1
  - trigger: time
    at: !input time_check_2
  - trigger: event
    event_type: battery_notes_battery_threshold
    event_data:
      battery_low: true
  - trigger: event
    event_type: battery_notes_battery_not_reported

action:
  - choose:
      # ----------------------------------------------------------
      # OPTION 1: Run the scan (Triggered by Time)
      # ----------------------------------------------------------
      - conditions:
          - condition: or
            conditions:
              - condition: trigger
                id: "0"
              - condition: trigger
                id: "1"
        sequence:
          - action: battery_notes.check_battery_low
          - action: battery_notes.check_battery_last_reported
            data:
              days_last_reported: !input offline_days

      # ----------------------------------------------------------
      # OPTION 2: Send Notification (Triggered by Event)
      # ----------------------------------------------------------
      - conditions:
          - condition: or
            conditions:
              - condition: template
                value_template: "{{ trigger.event.event_type == 'battery_notes_battery_threshold' }}"
              - condition: template
                value_template: "{{ trigger.event.event_type == 'battery_notes_battery_not_reported' }}"
        sequence:
          # Prepare the text variables for the user
          - variables:
              device_name: "{{ trigger.event.data.device_name }}"
              battery_level: "{{ trigger.event.data.battery_level | default('Unknown') }}"
              days_silent: "{{ trigger.event.data.battery_last_reported_days | default(0) }}"
              battery_qty: "{{ trigger.event.data.battery_quantity }}"
              battery_type: "{{ trigger.event.data.battery_type }}"
              title: "⚠️ Battery Alert: {{ device_name }}"
              message: >
                {% if trigger.event.event_type == 'battery_notes_battery_threshold' %}
                  Battery is low ({{ battery_level }}%).
                {% else %}
                  Device hasn't reported in {{ days_silent }} days.
                {% endif %}
                
                Buy: {{ battery_qty }}x {{ battery_type }}
          
          # Execute the user's chosen notification action
          - action: !input notification_action
